import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';

// Components
import Header from '@/app/Header';

import "./globals.css";


const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: ReactNode }>) {
    return (
        <html lang="en">
            <body className="bg-background text-foreground flex flex-col h-screen" style={inter.style}>
                <Header />
                {children}
            </body>
        </html>
    );
}
